<a href="https://colab.research.google.com/github/sallismael32/Personal_finance/blob/master/Copy_of_predict_Low_of_Day.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
sns.set()
import pandas_datareader as web



/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [44]:
s=["AMZN","NFLX","AAPL","GOOGL","GOOG","FB","NVDA","MSFT","TSLA","CTAS","PFE","GM","F","NKE"]


In [27]:
ticker=s[0]

In [29]:
df= web.DataReader(ticker,data_source='yahoo',start='2020-07-20',end='today')

In [30]:

df.tail(2)

High          Low  ...   Volume    Adj Close
Date                                  ...                      
2020-08-06  3247.469971  3165.429932  ...  3940600  3225.000000
2020-08-07  3240.810059  3140.669922  ...  3929600  3167.459961

[2 rows x 6 columns]

In [31]:
df['daily_return']=df['Adj Close'].pct_change()
df['low_vs_Open']=100*(-df['Open']+df['Low'])/(df['Open'])
df['high_vs_low']=100*(df['High']-df['Low'])/df['High']
#df['differ']=df['high_vs_low']-df['daily_return']
df['low_Close']=100*(df['Adj Close']-df['Low'])/(df['Adj Close'])
df['previous_Open']=df['Open'].shift(1)
df['previous_Adj']=df['Adj Close'].shift(1)
df['previous_High']=df['High'].shift(1)
df['previous_Low']=df['Low'].shift(1)
df['previous_Volume']=df['Volume'].shift(1)
df['previous_close']=df['Close'].shift(1)
df['Low_avr_5']=df['Low'].rolling(5).mean()
df['Close_avr_5']=df['Adj Close'].rolling(5).mean()
df['Open_Close']=df['Open']-df['previous_Adj']

In [32]:
df.head(3)

High          Low  ...  Close_avr_5  Open_Close
Date                                  ...                         
2020-07-20  3201.360107  2994.020020  ...          NaN         NaN
2020-07-21  3240.580078  3105.719971  ...          NaN   35.649902
2020-07-22  3150.000000  3065.260010  ...          NaN  -13.290039

[3 rows x 19 columns]

In [33]:
df.columns

Index(['High', 'Low', 'Open', 'Close', 'Volume', 'Adj Close', 'daily_return',
       'low_vs_Open', 'high_vs_low', 'low_Close', 'previous_Open',
       'previous_Adj', 'previous_High', 'previous_Low', 'previous_Volume',
       'previous_close', 'Low_avr_5', 'Close_avr_5', 'Open_Close'],
      dtype='object')

In [34]:
X=df[['Open','previous_Open','previous_Volume','previous_High','previous_Low','previous_close','Low_avr_5','Close_avr_5','Open_Close']].iloc[5:-1]
x1=df[['Open','previous_Open','previous_Volume','previous_High','previous_Low','previous_close','Low_avr_5','Close_avr_5','Open_Close']].iloc[1::]
y=df[['Low','Adj Close','High']].iloc[5:-1]

In [35]:
reg=LinearRegression().fit(X,y)
reg.coef_

array([[ 3.46178938e-01,  7.11850601e-01,  4.40546425e-06,
        -9.29313457e-01,  1.98488064e-01, -1.02761304e-01,
        -9.24059482e-01,  2.16735645e+00,  4.48940242e-01],
       [ 4.80295932e-03,  1.31833571e+00,  3.10133838e-05,
        -1.48339401e+00,  1.29023879e+00, -1.18655542e+00,
        -9.85778543e+00,  1.25883322e+01,  1.19135838e+00],
       [ 5.44697135e-01,  2.29349854e-01,  3.84901521e-06,
        -1.44327628e+00,  2.61085824e-01,  5.69010261e-01,
         2.98077495e+00, -2.14014902e+00, -2.43131260e-02]])

In [38]:
reg.score(X,y)

/usr/local/lib/python3.6/dist-packages/sklearn/base.py:434: FutureWarning: The default value of multioutput (not exposed in score method) will change from 'variance_weighted' to 'uniform_average' in 0.23 to keep consistent with 'metrics.r2_score'. To specify the default value manually and avoid the warning, please either call 'metrics.r2_score' directly or make a custom scorer with 'metrics.make_scorer' (the built-in scorer 'r2' uses multioutput='uniform_average').
  "multioutput='uniform_average').", FutureWarning)


1.0

In [39]:
reg.intercept_

array([-1472.18298163, -5549.78395138,   222.13423852])

In [40]:
#df[['Close','Open']].loc['2020-07-23']

In [41]:
b=x1.iloc[-2]
b
l=pd.DataFrame(b) #columns=[['Open','previous_Volume','previous_Open','previous_High','previous_low']])
#O=l
O=l.T
O

Open  previous_Open  ...  Close_avr_5  Open_Close
2020-08-06  3194.360107     3143.77002  ...  3169.085986  -10.669922

[1 rows x 9 columns]

In [42]:
c=reg.predict(O)
c

array([[3165.42993164, 3225.        , 3247.4699707 ]])

In [ ]:
c.shape

(1, 3)

In [ ]:
print('Low,Close,High')

Low,Close,High


In [43]:
df[['Low','Close','High','Open']].iloc[6::]

Low        Close         High         Open
Date                                                          
2020-07-28  2995.760010  3000.330078  3077.090088  3054.270020
2020-07-29  2996.770020  3033.530029  3039.159912  3030.989990
2020-07-30  3005.000000  3051.879883  3092.000000  3014.000000
2020-07-31  3151.000000  3164.679932  3246.820068  3244.000000
2020-08-03  3104.000000  3111.889893  3184.000000  3180.510010
2020-08-04  3101.209961  3138.830078  3167.239990  3101.209961
2020-08-05  3127.300049  3205.030029  3213.590088  3143.770020
2020-08-06  3165.429932  3225.000000  3247.469971  3194.360107
2020-08-07  3140.669922  3167.459961  3240.810059  3224.010010

In [ ]:
t=c[0:-1,0]
#t.shape
yu=t.reshape(3414,1)
you=pd.DataFrame(yu)
you

ValueError: ignored

In [ ]:
ki=df['Low'].iloc[6:-1]
ki.reset_index(drop='True',inplace=True)

In [ ]:
new_ed=pd.concat([you,ki],axis=1)
#new_ed.rename(columns={0:'esti'})
new_ed['diff']=new_ed['Low']-new_ed[0]
new_ed['diff%']=new_ed['diff']*100/new_ed['Low']
new_ed

In [ ]:
#d=c.reshape(1,3) 
#d[0][1]
#(-df['previous_close'].iloc[-1]+d[0][1])#*100/df['Open'].iloc[-1]

In [ ]:
new_ed['diff%'].tail(252).plot(figsize=(14,8))

**Predict** **for** **tomorrow** the **Low** **price** **and** **the** **Close** **Price**

In [ ]:
new_ed['diff%'].describe()

count    3412.000000
mean       -0.027030
std         1.255873
min       -25.591031
25%        -0.428578
50%         0.214122
75%         0.613096
max         6.375410
Name: diff%, dtype: float64

In [ ]:
predict_next=df[['Adj Close','Open','Volume','High','Low','Close']].iloc[4:-2]
d=np.array(predict_next)

In [ ]:
pre=d.reshape(1,-1)
pre

array([[1.61100006e+01, 2.00000000e+01, 6.86690000e+06, ...,
        1.53481006e+03, 1.48700000e+03, 1.49910999e+03]])

In [ ]:
df['previous_close'].iloc[-1]

1487.489990234375